services:
  client:
    build: ./client
    ports:
      - "3000:80"
    restart: always

  server:
    build: ./server
    ports:
      - "5000:5000"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/app


# services:
#   client:
#     build:
#       context: ./client
#       dockerfile: Dockerfile.dev
#     volumes:
#       - ./client:/app
#       - /app/node_modules
#     ports:
#       - "3000:3000"
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     command: npm start

#   server:
#     build:
#       context: ./server
#       dockerfile: Dockerfile.dev
#     volumes:
#       - ./server:/app
#       - /app/node_modules
#     ports:
#       - "5000:5000"
#     command: nodemon server.js
